name: GitHub Actions Demo
on: 
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

jobs:

  Build:
    runs-on: ubuntu-latest
    environment:
      name: Development

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Check out code
        uses: actions/checkout@master
      
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      

  Test-local:
    runs-on: ubuntu-latest
    environment:
      name: Development

    needs: [Build]
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Check out code
        uses: actions/checkout@master
      
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test Application
        run: |
          FLASK_DEBUG=${{secrets.FLASK_DEBUG}} python app.py &
          sleep 5
          curl http://127.0.0.1:5000/

  DeployDev:
    runs-on: ubuntu-latest
    environment:
      name: Development
  
    needs: [Test-local]
    steps:
      - name: Deploy
        run: echo Deploying the app to aws ec2 instance

      - name: Deploy on ec2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          USER_NAME: ${{ secrets.USER_NAME }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          APP_DIR: ${{ secrets.APP_DIR }}
          SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
        
        run: |
          run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} "
            cd ${APP_DIR} &&
            git pull &&
            echo ${USER_PASSWORD} | sudo -S systemctl restart ${SERVICE_NAME} "