name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Initialize Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Check docker installed or not
        run: docker run hello-world

      - name: Push to docker hub
        uses: docker/build-push-action/@v1
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install pytest
      - name: Run test suite
        run: |
          pipenv run test -v