# name: Deploy app on aws using docker and GitHub actions/checkout
# on:
#   push:
#     branches: [ master ]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     environment:
#       name: Development
#     strategy:
#       matrix:
#         python-version: [3.8]
    
#     steps:
#       - name: checkout 
#         uses: actions/checkout@master

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-west-2

#       - name: login to Amazon ECR
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Build, tag, and push image to amazon ECR
#         env:
#           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#           ECR_REPOSITORY: github-actions
#           IMAGE_TAG: ${{ github.sha }}
#         run: |
#           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY .
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY
#           docker tag $ECR_REGISTRY/$ECR_REPOSITORY $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
#           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

#       - name: Logout of amazon ECR
#         if: always()
#         run: docker logout ${{ steps.login-ecr.outputs.registry }}




name: Deploy flask app to heroku using docker.

on:
  push:
    branches: [ master ]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Development
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3 #github action name
        with:
          
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}
          
          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          
          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          
          # Dockerfile directory
          dockerfile_directory: ./
          
          # Dockerfile name.
          dockerfile_name: Dockerfile
          
          # Additional options of docker build command.
          docker_options: "--no-cache"
          
          # Select the process type for which you want the docker container to be uploaded.
          process_type: web
