name: Deploy image on dockerhub

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Check out code
        uses: actions/checkout@master
      
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: docker login
        env:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $username -p $password
        
      - name: build docker image
        run: docker build . --file Dockerfile --tag awadh/node-test:$(date +%s)

      - name: docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/flaskimage


          












      # - name: Check docker installed or not
      #   run: docker run hello-world

      # - name: Push to docker hub
      #   uses: docker/build-push-action/@v1
      #   with:
      #     username: ${{secrets.DOCKER_USERNAME}}
      #     password: ${{secrets.DOCKER_PASSWORD}}
      #     repository: ${{secrets.DOCKERHUB_REPO}}
      #     tag_with_ref: true
       