name: Deploy app on aws using docker and GitHub actions/checkout
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: Development
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - name: checkout 
        uses: actions/checkout@master

      - name: Build image
        run: |
          docker build .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1